---
- name: Fetch AAP subscription manifest and Automation Hub token
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: rhvp.aap_subscription_artifacts.aap_subscription_artifacts
      vars:
        aap_artifacts_action: fetch
