---
- name: Generate offline token then fetch AAP subscription artifacts
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: rhvp.aap_subscription_artifacts.aap_subscription_artifacts
      vars:
        aap_artifacts_action: all
